# Generated by Django 4.1.3 on 2022-12-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='upload')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('product', models.ManyToManyField(blank=True, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tel', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('debtDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('payment', models.ManyToManyField(blank=True, to='store.payment')),
            ],
        ),
    ]
